# Generated by Django 4.0.5 on 2022-07-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo Producto')),
                ('cantidad', models.CharField(max_length=50, verbose_name='Cantidad')),
            ],
        ),
    ]
